sudo: false

language: node_js

node_js:
  - "6"
  - "8"
  - "9"

os:
  - linux
  - osx

env:
  - CXX=g++-4.8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcode-select --install; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

script:
  - npm run test
  - npm run codecov
