---
release_tags: &release_tags
  tags:
    only: /^v\d+(\.\d+){2}(-.*)?$/

# "Include" for unit tests definition.
unit_tests: &unit_tests
  steps:
    - checkout
    - run:
        name: Install modules and dependencies.
        command: npm install
    - run:
        name: Compiles typescript to javascript.
        command: npm run compile
    - run:
        name: Run unit tests.
        command: npm run test
    - run:
        name: Submit coverage data to codecov.
        command: npm run codecov
        when: always
  
gochecks: &gochecks
  steps:
   - checkout
   - run:
      name: Check that code is formatted.
      command: gofmtdiff=$(gofmt -s -d .) && if [ -n "$gofmtdiff" ]; then printf 'gofmt -s found:\n%s\n' "$gofmtdiff" && exit 1; fi
   - run:
      name: Install golint.
      command: go get -u github.com/golang/lint/golint
   - run:
      name: Run lint check.
      command: golintlint=$(golint ./...) && if [ -n "$golintlint" ]; then printf 'golint found:\n%s\n' "$golintlint" && exit 1; fi

npmaudit: &npmaudit
  steps:
    - checkout
    - run:
        name: Run npm security audit.
        command: npm audit

version: 2.0
workflows:
  version: 2
  tests:
    jobs:
      - node6:
           filters: *release_tags
      - node8:
           filters: *release_tags
      - node9:
          filters: *release_tags
      - node10:
          filters: *release_tags
      - gocheck:
          filters: *release_tags
      - npmaudit:
          filters: *release_tags
      - publish_npm:
          requires:
            - node6
            - node8
            - node9
            - gocheck
            - npmaudit
          filters:
            branches:
              ignore: /.*/
            <<: *release_tags

jobs:
  node6:
    docker:
      - image: node:6@sha256:85a878cb14deb5a5a59944e906d43ef400e182e9fcc81a6beb18907f52309261
        user: node
    <<: *unit_tests
  node8:
    docker:
      - image: node:8@sha256:f10c8218e3f92b513af9120f5eda5fed35b651343f940881d696b958cc16ab43
        user: node
    <<: *unit_tests
  node9:
    docker:
      - image: node:9@sha256:ec1bc675cbcb0c5215af40c7c1b7a8ea9d5f17b084eaf7b4b4e69e0963a38f26
        user: node
    <<: *unit_tests
  node10:
    docker:
      - image: node:10@sha256:c00e4cb3acfb2a0c4997ddb0e809cba37f9f6cce43efa9a6e6f7f1a79e094ab5
        user: node
    <<: *unit_tests
  npmaudit:
    docker:
      - image: node:10@sha256:c00e4cb3acfb2a0c4997ddb0e809cba37f9f6cce43efa9a6e6f7f1a79e094ab5
        user: node
    dependencies:
      pre:
        - npm install npm@latest -g
    <<: *npmaudit
  gocheck:
    docker:
      - image: circleci/golang:1.9@sha256:78d0c5082e4e811e44f6a0d35fc15aadf29aac6ed30956633154adb9e21fecbb
    <<: *gochecks

  publish_npm:
    docker:
      - image: node:8@sha256:f10c8218e3f92b513af9120f5eda5fed35b651343f940881d696b958cc16ab43
        user: node
    steps:
      - checkout
      - run:
          name: Set NPM authentication.
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Install modules and dependencies.
          command: npm install
      - run:
          name: Publish the module to npm.
          command: npm publish

